const students = {
  "Aiden S": {title: "Adventure of a Lifetime", src: "https://trinket.io/embed/python3/b7bf4d1529?outputOnly=true&runOption=run&start=result"},
  "Anna Liu": {title: "Story Maker", src: "https://trinket.io/embed/python3/df0f6a2d26?outputOnly=true&runOption=run&start=result"},
  "Billy O": {title: "Quiz", src: "https://trinket.io/embed/python3/e5db8e500f?outputOnly=true&runOption=run&start=result"},
  "Brighton C": {title: "Pokemon", src: "https://trinket.io/embed/python/205b7cb006?outputOnly=true&runOption=run&start=result"},
  "Britton B": {title: "Jeopardy", src: "https://trinket.io/embed/python/d4efb63b1d?outputOnly=true&runOption=run&start=result"},
  "Chandler L": {title: "Tic-Tac-Toe", src: "https://trinket.io/embed/python3/b14bc88c26?outputOnly=true&runOption=run&start=result"},
  "Daniela A": {title: "Impossible Quiz", src: "https://trinket.io/embed/python/c1ace36416?outputOnly=true&runOption=run&start=result"},
  "Dylan G": {title: "Pokemon", src: "https://trinket.io/embed/python3/ac330ad94b?outputOnly=true&runOption=run&start=result"},
  "Emil P": {title: "Rock Paper Scissors", src: "https://trinket.io/embed/python3/420f9c5950?outputOnly=true&runOption=run&start=result"},
  "Emme T": {title: "Snake", src: "https://trinket.io/embed/python/4c950d51c2?outputOnly=true&start=result&start=result"},
  "Ethan B": {title: "Website", src: "https://computer-science-project--ethanbenson.repl.co/"},
  "Erick R": {title: "Quiz", src: "https://trinket.io/embed/python/70f2db8fbf?outputOnly=true&runOption=run&start=result"},
  "Forrest P": {title: "Password Generator", src: "https://trinket.io/embed/python3/d984195cb0?outputOnly=true&runOption=run&start=result"},
  "Hailey B": {title: "Rock Paper Scissors", src: "https://trinket.io/embed/python3/9c9feecf2f?outputOnly=true&runOption=run&start=result"},
  "Isaac G": {title: "Kobe", src: "https://trinket.io/embed/python/9190548c16?outputOnly=true&start=result"},
  "Ivy D": {title: "Desert Island", src: "https://trinket.io/embed/python/8031c79c98?outputOnly=true&runOption=run&start=result"},
  "Jacob J": {title: "Emoji Generator", src: "https://trinket.io/embed/python/ce9eea6fdc?outputOnly=true&runOption=run&start=result"},
  "Kaleb S": {title: "Hangman", src: "https://trinket.io/embed/python3/946629dfa1?outputOnly=true&runOption=run&start=result"},
  "Kyle G": {title: "Wisp's Tale", src: "https://trinket.io/embed/python3/1979560edc?outputOnly=true&runOption=run&start=result"},
  "Miriam T": {title: "Quiz", src: "https://trinket.io/embed/python/6ed3da70ad?outputOnly=true&runOption=run&start=result"},
  "Rebekah S": {title: "Chutes and Ladders", src: "https://trinket.io/embed/python3/da581f10c4?outputOnly=true&runOption=run&start=result"},
  "Reese A": {title: "Reese/Taylan Quiz", src: "https://trinket.io/embed/python3/4b924f9b85?outputOnly=true&runOption=run&start=result"},
  "Sadie A": {title: "Haunted House", src: "https://trinket.io/embed/python/e5de8392ca?outputOnly=true&runOption=run&start=result"},
  "Sam W": {title: "Choose Your Own Adventure", src: "https://trinket.io/embed/python/bad5dac1cd?outputOnly=true&runOption=run&start=result"},
  "Savannah W": {title: "Rock Paper Scissors", src: "https://trinket.io/embed/python3/9b1ab747ec?outputOnly=true&runOption=run&start=result"},
  "Sophia S": {title: "Adventure in the Forest", src: "https://trinket.io/embed/python/b21accc6f9?outputOnly=true&runOption=run&start=result"},
  "Taylan H": {title: "Princess Quiz", src: "https://trinket.io/embed/python3/24a89dc8e3?outputOnly=true&runOption=run&start=result"},
  "Xander E": {title: "Standoff", src: "https://trinket.io/embed/python/5e66f0293d?outputOnly=true&runOption=run&start=result"},
}

export default students;